import { APP_CONSTANTS } from "@/constants";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="min-h-screen bg-[#FFFBF2] flex flex-col items-center justify-center p-4 border-[12px] border-[#800000] rounded-lg relative ">
          {children}
          <footer className="absolute bottom-4 text-sm text-[#800000] font-mono">
            {APP_CONSTANTS.MADE_WITH_LOVE}
          </footer>
        </div>
      </body>
    </html>
  );
}
